<x-student-layout>
    <!-- Import Font Fredoka -->
    <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@400;600;700;900&display=swap" rel="stylesheet">
    <style>
        .font-fredoka {
            font-family: 'Fredoka', sans-serif;
        }

        .brutal-border {
            border: 4px solid #000000 !important;
        }

        .brutal-shadow {
            box-shadow: 6px 6px 0px 0px #000000 !important;
        }

        .brutal-shadow-sm {
            box-shadow: 3px 3px 0px 0px #000000 !important;
        }

        .brutal-hover {
            transition: all 0.2s ease-in-out !important;
        }

        .brutal-hover:hover {
            transform: translate(-3px, -3px) !important;
            box-shadow: 9px 9px 0px 0px #000000 !important;
        }

        .brutal-hover:active {
            transform: translate(2px, 2px) !important;
            box-shadow: 2px 2px 0px 0px #000000 !important;
        }
    </style>

    <div class="max-w-4xl w-full px-4 py-8 flex flex-col items-center font-fredoka text-black">

        <!-- Back to Dashboard / Header -->
        <div class="w-full flex justify-between items-center mb-6">
            <a href="{{ route('dashboard') }}"
                class="bg-[#FFB3B3] text-black px-4 py-2.5 rounded-2xl font-black brutal-border brutal-shadow-sm brutal-hover flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="3"
                    stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
                </svg>
            </a>
        </div>

        <!-- Progress Bar -->
        <div class="w-full mb-8 max-w-3xl">
            <div class="flex justify-between mb-3 items-end">
                <span class="font-black text-lg tracking-widest uppercase">Soal {{ $soal }} dari 10</span>
                <span class="text-sm font-bold text-slate-600">Progres: {{ ($soal - 1) * 10 }}%</span>
            </div>
            <div class="w-full h-7 bg-white brutal-border brutal-shadow-sm rounded-2xl overflow-hidden p-1">
                <div class="h-full bg-[#E0BBE4] rounded-xl transition-all duration-500 border-r-4 border-black"
                    style="width: {{ ($soal / 10) * 100 }}%"></div>
            </div>
        </div>

        <!-- Question Container -->
        <div
            class="w-full bg-[#FFFEFA] brutal-border brutal-shadow rounded-[2.5rem] p-6 md:p-10 mb-8 transition-all duration-300">
            <div class="text-center mb-6">
                <span
                    class="inline-block px-4 py-1.5 bg-[#BEE9E8] brutal-border brutal-shadow-sm rounded-xl text-xs font-black uppercase tracking-wider mb-3">Spasial</span>
                <h2 class="text-2xl md:text-3xl font-black text-black leading-snug">
                    Susunlah puzzle di bawah ini menjadi gambar anak-anak dari berbagai daerah!
                </h2>
                <p class="text-sm text-slate-500 mt-2 font-bold uppercase tracking-widest">👆 Klik 2 kepingan puzzle
                    untuk menukar posisinya!</p>
            </div>

            <!-- Puzzle and Reference Area -->
            <div class="flex flex-col md:flex-row gap-8 items-stretch justify-center max-w-3xl mx-auto">
                <!-- Left: 3x3 Puzzle Board -->
                <div
                    class="w-full md:w-3/5 flex flex-col justify-center bg-[#BEE9E8] brutal-border brutal-shadow rounded-[2rem] p-4">
                    <div id="puzzle-board" class="grid grid-cols-3 grid-rows-3 gap-2 w-full bg-[#BEE9E8]"
                        style="aspect-ratio: 1000 / 564;">
                        <!-- Slices generated by Javascript -->
                    </div>
                </div>

                <!-- Right: Reference Image Card -->
                <div class="w-full md:w-2/5 flex flex-col gap-4">
                    <div
                        class="bg-white brutal-border brutal-shadow-sm rounded-[2rem] p-6 flex flex-col items-center justify-center flex-grow text-center">
                        <span class="text-xs font-black uppercase tracking-widest text-slate-500 mb-3">Target
                            Gambar</span>
                        <div class="w-full brutal-border rounded-2xl overflow-hidden bg-slate-50 relative flex items-center justify-center"
                            style="aspect-ratio: 1000 / 564; max-width: 240px;">
                            @php
                                $imageName = 'anak_bercerita_komik.png';
                                $imagePath = 'images/evaluasi/' . $imageName;
                                $fileExists = file_exists(public_path($imagePath));
                            @endphp
                            @if ($fileExists)
                                <img src="{{ asset($imagePath) }}" alt="Target" class="w-full h-full object-cover">
                            @else
                                <div
                                    class="w-full h-full flex flex-col items-center justify-center p-3 bg-yellow-50 text-center text-black">
                                    <span class="text-2xl mb-1">🖼️</span>
                                    <span
                                        class="font-black text-[9px] uppercase tracking-wider text-slate-700">Aset:</span>
                                    <span
                                        class="font-bold text-[10px] bg-white px-1.5 py-0.5 brutal-border mt-1 font-mono text-slate-800 break-all">{{ $imageName }}</span>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Navigation Buttons -->
        <div class="flex gap-4 items-center">
            <a href="{{ route('evaluasi.soal', ['soal' => $soal - 1]) }}"
                class="bg-white hover:bg-slate-50 brutal-border brutal-shadow-sm brutal-hover text-black px-6 py-4 rounded-2xl font-black uppercase text-base flex items-center gap-2">
                Kembali
            </a>

            <button id="btn-next" onclick="goNext()"
                class="bg-[#D4F1BE] brutal-border brutal-shadow-sm brutal-hover text-black px-8 py-4 rounded-2xl font-black uppercase text-base flex items-center gap-2">
                Lanjut
            </button>
        </div>
    </div>

    <script>
        const imageSrc = "{{ asset('images/evaluasi/anak_bercerita_komik.png') }}";
        const hasImage = {{ $fileExists ? 'true' : 'false' }};
        const rows = 3;
        const cols = 3;
        const totalPieces = rows * cols;

        let shuffledPieces = [];
        let firstSelection = null;

        window.onload = function() {
            if (hasImage) {
                // Slice image using canvas
                const img = new Image();
                img.src = imageSrc;
                img.onload = function() {
                    const board = document.getElementById('puzzle-board');
                    board.style.aspectRatio = `${img.width} / ${img.height}`;

                    const pW = img.width / cols;
                    const pH = img.height / rows;
                    const pieces = [];

                    for (let i = 0; i < totalPieces; i++) {
                        const canvas = document.createElement('canvas');
                        canvas.width = pW;
                        canvas.height = pH;
                        const ctx = canvas.getContext('2d');
                        const sx = (i % cols) * pW;
                        const sy = Math.floor(i / cols) * pH;
                        ctx.drawImage(img, sx, sy, pW, pH, 0, 0, pW, pH);
                        pieces.push({
                            id: i,
                            data: canvas.toDataURL()
                        });
                    }

                    // Shuffle or restore state
                    initPuzzle(pieces);
                };
                img.onerror = function() {
                    // Fallback to text labels if image load fails
                    fallbackPuzzle();
                }
            } else {
                fallbackPuzzle();
            }
        };

        function fallbackPuzzle() {
            const board = document.getElementById('puzzle-board');
            board.style.aspectRatio = '1 / 1';

            const pieces = [];
            const labels = ['Bagian 1', 'Bagian 2', 'Bagian 3', 'Bagian 4', 'Bagian 5', 'Bagian 6', 'Bagian 7', 'Bagian 8',
                'Bagian 9'
            ];
            for (let i = 0; i < totalPieces; i++) {
                pieces.push({
                    id: i,
                    data: null,
                    label: labels[i]
                });
            }
            initPuzzle(pieces);
        }

        function initPuzzle(pieces) {
            // Restore state if available
            const stored = sessionStorage.getItem('evaluasi_answers');
            let savedOrder = null;
            if (stored) {
                const answers = JSON.parse(stored);
                if (answers.soal4) {
                    savedOrder = answers.soal4.split('-').map(Number);
                }
            }

            if (savedOrder && savedOrder.length === totalPieces) {
                // Restore the saved order
                shuffledPieces = savedOrder.map(id => pieces.find(p => p.id === id));
            } else {
                // Generate a random order that is shuffled
                shuffledPieces = [...pieces];
                // Shuffle until not in perfect order
                do {
                    shuffledPieces.sort(() => Math.random() - 0.5);
                } while (shuffledPieces.map(p => p.id).join('-') === '0-1-2-3-4-5-6-7-8');

                saveState();
            }

            renderPuzzle();
        }

        function renderPuzzle() {
            const board = document.getElementById('puzzle-board');
            board.innerHTML = shuffledPieces.map((p, index) => {
                const isSelected = firstSelection === index;
                const borderStyle = isSelected ? 'border: 4px solid #FFF5B8;' : 'border: 3px solid #000;';
                const shadowStyle = isSelected ? 'box-shadow: 0 0 0 4px #FFF5B8;' :
                    'box-shadow: 3px 3px 0px 0px #000;';

                return `
                    <button onclick="handlePieceClick(${index})"
                        class="relative overflow-hidden rounded-xl bg-white transition-all cursor-pointer flex items-center justify-center p-0.5 w-full h-full"
                        style="${borderStyle} ${shadowStyle}">
                        ${p.data ? `
                                                <img src="${p.data}" class="w-full h-full object-cover rounded-lg pointer-events-none">
                                            ` : `
                                                <div class="w-full h-full flex flex-col items-center justify-center bg-[#FFF9F0] pointer-events-none">
                                                    <span class="text-xs font-black text-slate-800">${p.label}</span>
                                                    <span class="text-[10px] text-slate-400 mt-1 font-mono">ID: ${p.id + 1}</span>
                                                </div>
                                            `}
                    </button>
                `;
            }).join('');
        }

        function handlePieceClick(index) {
            if (firstSelection === null) {
                firstSelection = index;
                renderPuzzle();
            } else {
                // Swap
                const temp = shuffledPieces[firstSelection];
                shuffledPieces[firstSelection] = shuffledPieces[index];
                shuffledPieces[index] = temp;
                firstSelection = null;
                renderPuzzle();
                saveState();
            }
        }

        function saveState() {
            const orderStr = shuffledPieces.map(p => p.id).join('-');
            const stored = sessionStorage.getItem('evaluasi_answers') || '{}';
            const answers = JSON.parse(stored);
            answers.soal4 = orderStr;
            sessionStorage.setItem('evaluasi_answers', JSON.stringify(answers));
        }

        function goNext() {
            window.location.href = "{{ route('evaluasi.soal', ['soal' => $soal + 1]) }}";
        }
    </script>
</x-student-layout>
